/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VLibro.java
 *
 * Created on 16-feb-2011, 18:17:07
 */

package gui;

import aplicacion.Usuario;
import aplicacion.Prestamo;
import java.sql.Date;

import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import aplicacion.Ejemplar;
import javax.swing.JOptionPane;

/**
 *
 * @author basesdatos
 */
public class VPrestamos extends javax.swing.JDialog {

    private aplicacion.FachadaAplicacion fa;
    private Ejemplar ejemplar;
    
    /** Creates new form VLibro */
    public VPrestamos(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Ejemplar ejemplar) {
        super(parent, true);
        this.fa = fa;
        initComponents();
        this.ejemplar=ejemplar;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnPrestar = new javax.swing.JButton();
        jLabelIdArriba = new javax.swing.JLabel();
        textIdArriba = new javax.swing.JTextField();
        jLabelNombreArriba = new javax.swing.JLabel();
        textNombreArriba = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblPres = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de usuarios");
        setResizable(false);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnPrestar.setText("Prestar");
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });

        jLabelIdArriba.setText("Id:");

        jLabelNombreArriba.setText("Nombre:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblPres.setModel(new ModeloTablaPrestamos());
        tblPres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPresMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblPres);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnPrestar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(85, 85, 85))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelIdArriba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textIdArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabelNombreArriba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textNombreArriba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdArriba)
                    .addComponent(textIdArriba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreArriba)
                    .addComponent(textNombreArriba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrestar)
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
        // TODO add your handling code here:
        ModeloTablaPrestamos mp=(ModeloTablaPrestamos) tblPres.getModel();
        if (mp.obtenerUsuario(tblPres.getSelectedRow())!=null) {
            Prestamo prestamo = new Prestamo(new Date(System.currentTimeMillis()), null, null, ejemplar, mp.obtenerUsuario(tblPres.getSelectedRow()));
            fa.realizarPrestamo(prestamo);
            btnPrestar.setEnabled(false);
        }
    }//GEN-LAST:event_btnPrestarActionPerformed

    private void tblPresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPresMouseClicked
        // TODO add your handling code here:
        ModeloTablaPrestamos mp=(ModeloTablaPrestamos) tblPres.getModel();
        
        int valorUltimo=Integer.parseInt(tblPres.getValueAt(tblPres.getSelectedRow(), 3).toString());
        if(valorUltimo==0){
            btnPrestar.setEnabled(true);
        }
        else{
            btnPrestar.setEnabled(false);
        }
    }//GEN-LAST:event_tblPresMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        BuscarPrestamos();
    }// GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }// GEN-LAST:event_btnSalirActionPerformed

    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabelIdArriba;
    private javax.swing.JLabel jLabelNombreArriba;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblPres;
    private javax.swing.JTextField textIdArriba;
    private javax.swing.JTextField textNombreArriba;
    // End of variables declaration//GEN-END:variables
    
    private void BuscarPrestamos(){
        ModeloTablaPrestamos mtp;

        mtp=(ModeloTablaPrestamos) tblPres.getModel();
        java.util.List<Usuario> usrs = fa.obtenerUsuarios(textIdArriba.getText(), textNombreArriba.getText());
        mtp.setFilas(usrs, fa.obtenerPrestamosVencidos(usrs));
        if (mtp.getRowCount() > 0) {
            tblPres.setRowSelectionInterval(0, 0);
            btnPrestar.setEnabled(true);
            
            int lineaseleccion=tblPres.getSelectedRow();
            Usuario usuario=mtp.obtenerUsuario(lineaseleccion);
            
        }
        else btnPrestar.setEnabled(false);
 
    }
    
}
