/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VLibro.java
 *
 * Created on 16-feb-2011, 18:17:07
 */

package gui;

import aplicacion.Libro;
import aplicacion.TipoUsuario;
import aplicacion.Usuario;

import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import aplicacion.Ejemplar;
import javax.swing.JOptionPane;

/**
 *
 * @author basesdatos
 */
public class VGestionUsuarios extends javax.swing.JDialog {

    private java.util.List<String> usuariosBorrados;
    private VPrincipal padre;
    private aplicacion.FachadaAplicacion fa;
    private boolean creandoUsuario;

    /** Creates new form VLibro */
    public VGestionUsuarios(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa) {
        super(parent, modal);
        this.fa = fa;
        initComponents();
        padre = (VPrincipal) parent;
        btnNuevo.setEnabled(true);
        this.usuariosBorrados = new java.util.ArrayList<String>();

        ModeloTablaUsuarios mTablaU = new ModeloTablaUsuarios();
        lstUsuarios.setModel(mTablaU);

        mTablaU.setFilas(fa.obtenerUsuarios(textIdArriba.getText(), textNombreArriba.getText()));
        lstUsuarios.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lstUsuarios.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // TODO Auto-generated method stub
                if (lstUsuarios.getSelectedRow() >= 0) {
                    Usuario u = mTablaU.getFilas().get(lstUsuarios.getSelectedRow());
                    actualizarDatos(u);
                    btnBorrar.setEnabled(true);
                    btnGuardar.setEnabled(true);
                }
            }
        });

        btnBorrar.setEnabled(false);
        btnGuardar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jLabelIdArriba = new javax.swing.JLabel();
        textIdArriba = new javax.swing.JTextField();
        jLabelNombreArriba = new javax.swing.JLabel();
        textNombreArriba = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstUsuarios = new javax.swing.JTable();
        jLabelIdAbajo = new javax.swing.JLabel();
        textIdAbajo = new javax.swing.JTextField();
        textNombreAbajo = new javax.swing.JTextField();
        jLabelNombreAbajo = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelClave = new javax.swing.JLabel();
        textClave = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        textDireccion = new javax.swing.JTextField();
        jComboBoxTipo = new javax.swing.JComboBox<>();

        jTable1.setModel(
                new javax.swing.table.DefaultTableModel(
                        new Object[][] { { null, null, null, null }, { null, null, null, null },
                                { null, null, null, null }, { null, null, null, null } },
                        new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
        jScrollPane5.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de libros");
        setResizable(false);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jLabelIdArriba.setText("Id:");

        jLabelNombreArriba.setText("Nombre:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lstUsuarios
                .setModel(new javax.swing.table.DefaultTableModel(
                        new Object[][] { { null, null, null, null }, { null, null, null, null },
                                { null, null, null, null }, { null, null, null, null } },
                        new String[] { "Id", "Nombre", "Email", "Tipo" }));
        jScrollPane6.setViewportView(lstUsuarios);

        jLabelIdAbajo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelIdAbajo.setText("Id:");

        textIdAbajo.setEnabled(false);

        textNombreAbajo.setEnabled(false);

        jLabelNombreAbajo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNombreAbajo.setText("Nombre:");

        jLabelEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEmail.setText("Email:");

        jLabelClave.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelClave.setText("Clave:");

        textClave.setEnabled(false);

        textEmail.setEnabled(false);

        jLabelDireccion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDireccion.setText("Dirección:");

        jLabelTipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTipo.setText("Tipo:");

        textDireccion.setEnabled(false);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<TipoUsuario>(
                new TipoUsuario[] { TipoUsuario.Administrador, TipoUsuario.Normal }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup().addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                        .createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelNombreAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelIdAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textIdAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 98,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelClave, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textClave))
                                .addGroup(layout.createSequentialGroup().addGap(6, 6, 6).addComponent(textNombreAbajo)
                                        .addGap(73, 73, 73).addComponent(textEmail)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelDireccion, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textDireccion).addComponent(jComboBoxTipo,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, 170,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup().addComponent(jLabelIdArriba)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textIdArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 152,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18).addComponent(jLabelNombreArriba)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textNombreArriba)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscar))
                        .addComponent(jScrollPane6).addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(btnNuevo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnGuardar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 61,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                        layout.createSequentialGroup().addComponent(btnBorrar)
                                                                .addGap(273, 273, 273).addComponent(btnSalir)))))
                .addContainerGap()));

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { jLabelIdAbajo, jLabelTipo });

        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelIdArriba)
                                .addComponent(textIdArriba, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNombreArriba)
                                .addComponent(textNombreArriba, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(
                                jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 191,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(layout
                                .createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelIdAbajo)
                                        .addComponent(textIdAbajo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelClave).addComponent(textClave,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelNombreAbajo)
                                        .addComponent(textNombreAbajo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelEmail).addComponent(textEmail,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabelTipo).addComponent(jComboBoxTipo,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabelDireccion)
                                                .addComponent(textDireccion, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNuevo).addComponent(btnGuardar).addComponent(btnBorrar)
                                .addComponent(btnSalir))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        java.util.List<Usuario> usrs = fa.obtenerUsuarios(textIdArriba.getText(), textNombreArriba.getText());
        ((ModeloTablaUsuarios) lstUsuarios.getModel()).setFilas(usrs);
        actualizarDatos(new Usuario(null, null, null, null, null, null));
    }// GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }// GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        ModeloTablaUsuarios mu;
        Usuario u;

        mu = (ModeloTablaUsuarios) lstUsuarios.getModel();

        lstUsuarios.setRowSelectionInterval(0, 0);

        actualizarDatos(new Usuario(null, null, null, null, null, null));
        creandoUsuario = true;

        btnBorrar.setEnabled(true);
    }// GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        java.util.List<Usuario> usrs;
        java.util.List<Usuario> usrsInsertar = new java.util.ArrayList<Usuario>();

        ModeloTablaUsuarios mu = (ModeloTablaUsuarios) lstUsuarios.getModel();
        usrs = mu.getFilas();
        if (creandoUsuario) {
            usrsInsertar.add(new Usuario(textIdAbajo.getText(), textClave.getText(), textNombreAbajo.getText(),
                    textDireccion.getText(), textEmail.getText(), (TipoUsuario) jComboBoxTipo.getSelectedItem()));
        } else {
            usrs.set(lstUsuarios.getSelectedRow(),
                    new Usuario(textIdAbajo.getText(), textClave.getText(), textNombreAbajo.getText(),
                            textDireccion.getText(), textEmail.getText(),
                            (TipoUsuario) jComboBoxTipo.getSelectedItem()));
        }
        creandoUsuario = false;
        usrs = fa.actualizarUsuarios(usrs, usuariosBorrados, usrsInsertar);
        mu.setFilas(usrs);
        if (mu.getRowCount() > 0) {
            lstUsuarios.setRowSelectionInterval(0, 0);
            btnBorrar.setEnabled(true);
        } else
            btnBorrar.setEnabled(false);
    }// GEN-LAST:event_btnGuardarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        ModeloTablaUsuarios mu = (ModeloTablaUsuarios) lstUsuarios.getModel();
        if (mu.obtenerUsuario(lstUsuarios.getSelectedRow()).getIdUsuario() != null) {
            if (fa.obtenerPrestamos(mu.obtenerUsuario(lstUsuarios.getSelectedRow())).isEmpty()) {
                usuariosBorrados.add(mu.obtenerUsuario(lstUsuarios.getSelectedRow()).getIdUsuario());
            } else {
                fa.muestraExcepcion("No se puede borrar el usuario, tiene préstamos.");
            }
        }
        java.util.List<Usuario> usuariosActs = fa.actualizarUsuarios(mu.getFilas(), usuariosBorrados,
                new java.util.ArrayList<Usuario>());
        mu.setFilas(usuariosActs);
        usuariosBorrados.clear();
        if (mu.getRowCount() == 0) {
            btnBorrar.setEnabled(false);
        } else {
            lstUsuarios.setRowSelectionInterval(0, 0);
        }
    }// GEN-LAST:event_btnBorrarActionPerformed

    private void actualizarDatos(Usuario u) {
        creandoUsuario = false;
        textIdAbajo.setText(u.getIdUsuario());
        textClave.setText(u.getClave());
        textDireccion.setText(u.getDireccion());
        textEmail.setText(u.getEmail());
        textNombreAbajo.setText(u.getNombre());
        jComboBoxTipo.setSelectedItem(u.getTipoUsuario());
        textIdAbajo.setEnabled(true);
        textClave.setEnabled(true);
        textDireccion.setEnabled(true);
        textEmail.setEnabled(true);
        textNombreAbajo.setEnabled(true);
        jComboBoxTipo.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<aplicacion.TipoUsuario> jComboBoxTipo;
    private javax.swing.JLabel jLabelClave;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelIdAbajo;
    private javax.swing.JLabel jLabelIdArriba;
    private javax.swing.JLabel jLabelNombreAbajo;
    private javax.swing.JLabel jLabelNombreArriba;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable lstUsuarios;
    private javax.swing.JTextField textClave;
    private javax.swing.JTextField textDireccion;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textIdAbajo;
    private javax.swing.JTextField textIdArriba;
    private javax.swing.JTextField textNombreAbajo;
    private javax.swing.JTextField textNombreArriba;
    // End of variables declaration//GEN-END:variables

}
